# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'
        
    - name: Install dependencies
      run:
        go mod download
        
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache-dependency-path: go.sum
        
    - name: Build
      run: go build cmd/cart-api/cart-api.go

    - name: Test
      run: go test -v ./internal/services -json > TestResults-${{ matrix.go-version }}.json
    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json
